### ISSUE TITLE
What exactly makes this improved over the normal std?

### ISSUE THREAD

**Issue by LemonjamesD** [leddoo/sti#1]
I'm just wondering because I just stumbled across this as of right now.

**Comment by leddoo** [comment]
well, mostly it's just a funny name :D
it's basically my personal standard library.
it has stuff like allocators & simd (only aarch64 atm, i haven't done x86 yet), which std has, but aren't stable yet.
there's also some stuff for the common "handles instead of pointers" pattern (in the `keyed` module).
